source 'https://github.com/CocoaPods/Specs.git'
pod 'BlocksKit', :git => 'https://github.com/zwaldowski/BlocksKit.git'
pod 'pop', '~> 1.0'
pod 'RKCardView'
pod 'ParseFacebookUtils'
pod 'Facebook-iOS-SDK'
pod 'Parse'
pod 'MMWormhole'
pod 'JFParseFBFriends'
pod 'iCarousel'
pod 'RS3DSegmentedControl'